### ISSUE TITLE
Title is Lowercase

### ISSUE THREAD

**Issue by ceiselm** [amgreenstreet/BeliefMeToo#13]
**Summary**: Title is Lowercase
**Description**: This is a simple grammar aesthetic, but on the 'Report' page, the text title ("Hello from Reports") is lowercase and would look nicer as uppercase. Could be applied to the titles of the articles within the 'Welcome to Education' grid on the home page as well.
**Severity**: _enhancement_
**Suggestions**: Provide this on all pages for consistency.

**Comment by bdkinzer** [comment]
Fixed in commit edd716a
