### ISSUE TITLE
 Auto Refresh New Posts

### ISSUE THREAD

**Issue by ceiselm** [amgreenstreet/BeliefMeToo#15]
**Summary**: Auto Refresh New Posts
**Description**: Recently created new posts made by users on the 'Community' page don't show unless the user refreshes the entire website.
**Severity**: _critical_
**Suggestions**: Add pagination to the 'Community' page or provide feedback (a pop-up modal) to the user that the post has successfully been made and the user needs to refresh the page to see it.

**Comment by bdkinzer** [comment]
Fixed in commit f34b6d0. New posts immediately show after creation.
