### ISSUE TITLE
Menu Bar - Education Tab Text Lightening

### ISSUE THREAD

**Issue by ceiselm** [amgreenstreet/BeliefMeToo#20]
**Summary**: Menu Bar - Education Tab Text Lightening
**Description**: When navigating to the Menu Bar and clicking 'Education' which brings you to the Education tab, the 'Education' text does not indicate you're on the page by lightening in color like the other clickable menu items.
**Severity**: _trivial_
**Suggestions**: n/a

**Comment by bdkinzer** [comment]
Fixed in commit f6512cf by removing 'active' from tab bar.
